import { keyMirror } from "../utils/commonUtils";

export default keyMirror({
  /* UI */
  EXIT_APP: null,
  SET_UPLOAD_PANEL_TAB: null,
  BULK_FLUSH: null,
  SHOW_PHOTO_PREVIEW_MODAL: null,
  HIDE_PHOTO_PREVIEW_MODAL: null,
  SHOW_UPLOAD_PANEL: null,
  HIDE_UPLOAD_PANEL: null,

  /* AppInfo */
  REQUEST_GET_PRINT_SIZE_INFO: null,
  REQUEST_GET_PRINT_SIZE_INFO_SUCCESS: null,
  REQUEST_GET_PRINT_SIZE_INFO_ERROR: null,

  REQUEST_GET_UPLOADING_SERVER_URL: null,
  REQUEST_GET_UPLOADING_SERVER_URL_SUCCESS: null,
  REQUEST_GET_UPLOADING_SERVER_URL_ERROR: null,

  REQUEST_GET_PLUS_PRODUCTS: null,
  REQUEST_GET_PLUS_PRODUCTS_SUCCESS: null,
  REQUEST_GET_PLUS_PRODUCTS_ERROR: null,

  REQUEST_GET_ORDERING_SERVER_URL: null,
  REQUEST_GET_ORDERING_SERVER_URL_SUCCESS: null,
  REQUEST_GET_ORDERING_SERVER_URL_ERROR: null,

  /* PhotoAppender */
  OPEN_PHOTO_APPENDER: null,
  CLOSE_PHOTO_APPENDER: null,
  SET_SELECTED_APPENDER: null,
  SET_PHOTO_APPENDER_MODAL_CONTENT: null,

  MARK_OR_UNMARK_PHOTO_TO_EDIT: null,

  CLEAR_MARKS: null,

  /* PhotoDirectUpload */
  SET_UPLOAD_COUNTS: null,

  APPEND_UPLOADS: null,
  SET_FILE_UPLOAD_END: null,

  REQUEST_FLUSH_UPLOADS: null,
  FLUSH_UPLOADS: null,

  REQUEST_BULK_UPLOAD_IMAGE_FILES: null,
  REQUEST_BULK_UPLOAD_IMAGE_FILES_SUCCESS: null,
  REQUEST_BULK_UPLOAD_IMAGE_FILES_ERROR: null,

  CREATE_IMAGE_UPLOAD: null,
  CREATE_IMAGE_UPLOAD_META: null,
  CREATE_IMAGE_UPLOAD_ERROR: null,

  DELETE_LOCAL_IMAGE_FILE: null,

  /* SmartBox */
  REQUEST_GET_SMARTBOX_AGREEMENT_STATE: null,
  REQUEST_GET_SMARTBOX_AGREEMENT_STATE_SUCCESS: null,
  REQUEST_GET_SMARTBOX_AGREEMENT_STATE_ERROR: null,

  REQUEST_UPDATE_SMARTBOX_AGREEMENT_STATE: null,
  REQUEST_UPDATE_SMARTBOX_AGREEMENT_STATE_SUCCESS: null,
  REQUEST_UPDATE_SMARTBOX_AGREEMENT_STATE_ERROR: null,

  REQUEST_GET_SMARTBOX_ENDPOINTS: null,
  REQUEST_GET_SMARTBOX_ENDPOINTS_SUCCESS: null,
  REQUEST_GET_SMARTBOX_ENDPOINTS_ERROR: null,

  ADD_TO_WORKSPACE: null,

  REQUEST_GET_SMARTBOX_PHOTOS: null,
  REQUEST_GET_SMARTBOX_PHOTOS_SUCCESS: null,
  REQUEST_GET_SMARTBOX_PHOTOS_ERROR: null,

  REQUEST_UPLOAD_IMAGE_FILE_TO_SMARTBOX_SUCCESS: null,
  REQUEST_UPLOAD_IMAGE_FILE_TO_SMARTBOX_ERROR: null,

  REQUEST_UPLOAD_IMAGE_FILES_TO_SMARTBOX: null,
  REQUEST_UPLOAD_IMAGE_FILES_TO_SMARTBOX_SUCCESS: null,
  REQUEST_UPLOAD_IMAGE_FILES_TO_SMARTBOX_ERROR: null,

  SET_SMARTBOX_UPLOAD_COUNTS: null,
  APPEND_SMARTBOX_UPLOADS: null,
  SET_SMARTBOX_FILE_UPLOAD_END: null,
  REQUEST_FLUSH_SMARTBOX_UPLOADS: null,
  FLUSH_SMARTBOX_UPLOADS: null,

  REQUEST_GET_SMARTBOX_ALBUMS: null,
  REQUEST_GET_SMARTBOX_ALBUMS_SUCCESS: null,
  REQUEST_GET_SMARTBOX_ALBUMS_ERROR: null,

  UPDATE_SMARTBOX_ALBUM: null,

  CHANGE_SMARTBOX_SIDEBAR_TAB: null,

  REQUEST_SMARTBOX_ADD_TO_NEW_ALBUM: null,
  REQUEST_SMARTBOX_ADD_TO_NEW_ALBUM_SUCCESS: null,
  REQUEST_SMARTBOX_ADD_TO_NEW_ALBUM_ERROR: null,

  REQUEST_SMARTBOX_ADD_TO_ALBUM: null,
  REQUEST_SMARTBOX_ADD_TO_ALBUM_SUCCESS: null,
  REQUEST_SMARTBOX_ADD_TO_ALBUM_ERROR: null,

  REQUEST_SMARTBOX_ADD_ALBUM: null,
  REQUEST_SMARTBOX_ADD_ALBUM_SUCCESS: null,
  REQUEST_SMARTBOX_ADD_ALBUM_ERROR: null,

  MARK_SMARTBOX_PHOTO: null,
  UNMARK_SMARTBOX_PHOTO: null,

  SHOW_SMARTBOX_ALBUM_MANAGE_PANEL: null,
  HIDE_SMARTBOX_ALBUM_MANAGE_PANEL: null,

  REQUEST_SMARTBOX_ADD_FAVORITES: null,
  REQUEST_SMARTBOX_ADD_FAVORITES_SUCCESS: null,
  REQUEST_SMARTBOX_ADD_FAVORITES_ERROR: null,

  REQUEST_SMARTBOX_DELETE_FAVORITES: null,
  REQUEST_SMARTBOX_DELETE_FAVORITES_SUCCESS: null,
  REQUEST_SMARTBOX_DELETE_FAVORITES_ERROR: null,

  REQUEST_SMARTBOX_ADD_OR_DELETE_FAVORITES: null,
  REQUEST_SMARTBOX_ADD_OR_DELETE_FAVORITES_SUCCESS: null,
  REQUEST_SMARTBOX_ADD_OR_DELETE_FAVORITES_ERROR: null,

  REQUEST_SMARTBOX_DELETE_PHOTOS: null,
  REQUEST_SMARTBOX_DELETE_PHOTOS_SUCCESS: null,
  REQUEST_SMARTBOX_DELETE_PHOTOS_ERROR: null,

  REQUEST_SMARTBOX_ADD_TAGS: null,
  REQUEST_SMARTBOX_ADD_TAGS_SUCCESS: null,
  REQUEST_SMARTBOX_ADD_TAGS_ERROR: null,

  /* PhotoEditor */
  SET_EDITOR_GRID_OPTIONS: null,

  APPEND_PHOTOS_TO_PHOTO_EDITOR: null,
  PURGE_PHOTOS: null,
  PURGE_SELECTED_PHOTOS: null,

  SELECT_ALL_PHOTOS: null,
  UNSELECT_ALL_PHOTOS: null,
  SELECT_OR_UNSELECT_PHOTO: null,
  SELECT_OR_UNSELECT_ALL_PHOTOS: null,
  SELECT_CLONE_PHOTO: null,

  SET_PRINT_OPTIONS: null,
  SET_PRINT_OPTIONS_ALL: null,

  UNDO: null,
  REDO: null,

  OPEN_DETAIL_EDITOR: null,
  CLOSE_DETAIL_EDITOR: null,
  ADJUST_DETAIL_EDITS: null,

  /* PhotoOrder */
  REQUEST_CREATE_ORDER: null,
  REQUEST_CREATE_ORDER_SUCCESS: null,
  REQUEST_CREATE_ORDER_ERROR: null,

  REQUEST_ADD_TO_CART: null,
  REQUEST_ADD_TO_CART_SUCCESS: null,
  REQUEST_ADD_TO_CART_ERROR: null,
});
